#define automatico auto
#define romper break
#define booleano bool
#define caso case
#define caracter char
#define constante const
#define continuar continue
#define por_defecto default
#define hace do
#define doble double
#define ademas else
#define enumerado enum
#define externo extern
#define falso false
#define flotante float
#define para for
#define ir_hasta goto
#define si if
#define enlinea inline
#define entero int
#define largo long
#define registro register
#define restringido restrict
#define retornar return
#define corto short
#define signado signed
#define tamaño_de sizeof
#define estatico static
#define estructura struct
#define cambio switch
#define verdadero true
#define definir_tipo typedef
#define union union
#define sin_signar unsigned
#define vacio void
#define volatil volatile
#define mientras while
